name: "Docker lint"

on: 
  pull_request:
    paths:
      - '.devcontainer/**'
      - '.docker/**'
      - '.github/workflows/**'

  push:
    paths:
      - '.docker/**'
      - '.github/workflows/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Dockerfile -> debian-clang.Dockerfile
        run: docker run --rm -i hadolint/hadolint hadolint --ignore DL3008  - < .devcontainer/Dockerfile
