name: "Shellcheck"

on: 
  pull_request:
    paths:
      - '.github/workflows/shellcheck.yml'
      - 'install.sh'

  push:
    paths:
      - '.github/workflows/shellcheck.yml'
      - 'install.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install shellcheck
      
      - name: Shellcheck
        run: shellcheck install.sh
